spring:
  profiles:
    active: local

  application:
    name: review-pannel
    ping: Hello from external configuration!

  datasource:
    url: "jdbc:mysql://localhost:3306/review_pannel"
    username: "root"
    password: "test1234"

  flyway:
    enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  servlet:
    context-path: /api/v1/
  error:
    include-message: always